export const WORKSPACE_SCALE = 12;
export const LAYOUT_SNAP_THRESHOLD_PX = 10;
export const CELL_SNAP_THRESHOLD_PX = 10;
export const DEFAULT_SHELF_OUTER_BORDER_INCHES = 1.5;
export const DEFAULT_SHELF_INNER_BORDER_INCHES = 0.75;
export const SHELF_BORDER_INCREMENT_INCHES = 0.25;
